"use client"
import { generateTextAction } from "@/app/actions/aiActions";
import { useState } from "react";
export default function Home() {

  const [prompt, setPrompt] = useState<string>("");
  const [output, setOutput] = useState<string>("");
  const handleSendPrompt = async () => {
    const response = await generateTextAction(prompt);
    setOutput(response);
  }

  return (
    <main className="flex w-screen h-screen flex-col items-center justify-between p-24 ">
      {output && (
        <div className="flex h-[calc(100vh-180px)] w-full items-center justify-center px-6">
  <div className="w-full max-w-4xl rounded-3xl border border-neutral-800 bg-neutral-900 shadow-2xl">
    {/* Header */}
    <div className="flex items-center gap-4 border-b border-neutral-800 px-8 py-5">
      <div className="flex h-12 w-12 items-center justify-center rounded-full bg-blue-600 text-lg font-bold">
        AI
      </div>

      <div>
        <h2 className="text-xl font-semibold text-white">
          Gemini Response
        </h2>
        <p className="text-sm text-neutral-400">
          Generated by ChatKaro AI
        </p>
      </div>
    </div>

    {/* Output */}
    <div className="max-h-[500px] overflow-y-auto px-8 py-6">
      <p className="whitespace-pre-wrap text-[17px] leading-8 text-neutral-200">
        {output}
      </p>
    </div>
  </div>
</div>
      )}
      <div className="flex items-center justify-center gap-4">
        <h1 className="text-3xl font-bold text-white">ChatKaro</h1>
      </div>
      <div className="flex items-center justify-center gap-4">
        <p className="text-lg text-white">Type your prompt below and click send to generate text using Google Gemini AI.</p>
      </div>
      <div className="input-area fixed bottom-6 px-24 py-2 *:bg-gray-100 w-full flex items-center justify-center gap-2 ">
        <input
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          className="bg-black text-gray-800 placeholder:text-gray-500 border border-gray-300 focus:outline-none focus:ring-2 focus:ring-blue-500 w-[80%]"
          placeholder="Type your message..."
        ></input>
        
        <button 
        onClick={handleSendPrompt}
        className=" w-[18%] rounded bg-neutral-600 px-4 py-2 text-red-900 hover:bg-blue-700 ">Send</button>
      </div>
    </main>
  );
}
